#!/bin/bash
#
# Make a new blog post
#

set -eu

if [[ $# -ne 1 ]]; then
    echo "usage: $0 title" 1>&2
    exit 1
fi

title="$1"
title_file=$(echo $title | tr " " "_" | tr "A-Z" "a-z")
datestamp=$(date '+%Y-%m-%d')
post="content/blog/${title_file}.md"

if [[ -f "$post" ]]; then
    echo "error: post $post already exists" 1>&2
    exit 2
fi

cat > $post << EOF
---
title: $title
date: $datestamp
author:
tags:
---


<div></div><!--more-->


EOF
echo "Created $post"
